# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.cache/wt} [current_project]
set_property parent.project_path {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/RegFile.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/mux2.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/instructionmemory.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/imm_Gen.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/flopr.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/datamemory.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/adder.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/alu.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/Controller.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/ALUController.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/Datapath.sv}
  {C:/Users/joshu/OneDrive/Documents/Winter 2018/CSE 132L/project_3/project_3.srcs/sources_1/imports/lab-2/design/RISC_V.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top riscv -part xc7k70tfbv676-1


write_checkpoint -force -noxdef riscv.dcp

catch { report_utilization -file riscv_utilization_synth.rpt -pb riscv_utilization_synth.pb }
